### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by 7gill** [confirmedcode/Lockdown-Mac#10]
I am trying to delete lockdown but it seems I don't know how. The Lockdown Mac Tunnel in the activity monitor keeps restarting. I can't trash the app without getting a "The item lockdown.app" can't be move to the Bin because some of its extensions are in use" message. Also, the folders in the containers folder keep red-awning as well. 

Any guidance would be greatly appreciated. 

Thanks

**Comment by hijohnnylin** [comment]
Hi, I just added the answer to this (as well as a bunch of other questions) to the new FAQ here: https://lockdownhq.com/faq

Let me know if that works.
