### ISSUE TITLE
BUG: Big Sur - Second-level popover's buttons/fields are broken.

### ISSUE THREAD

**Issue by hijohnnylin** [confirmedcode/Lockdown-Mac#14]
The second-level popover's button/fields are disabled in Big Sur.

**Comment by hijohnnylin** [comment]
Fixed in 1e6e903e37aee9f70dc5a777b07880a8af10aaf7. Currently verifying.

**Comment by CruiseMan** [comment]
> Fixed in [1e6e903](https://github.com/confirmedcode/Lockdown-Mac/commit/1e6e903e37aee9f70dc5a777b07880a8af10aaf7). Currently verifying.

Is this can be closed ?
