### ISSUE TITLE
STABILITY: Sometimes Secure Tunnel / Firewall takes a long time to disable.

### ISSUE THREAD

**Issue by hijohnnylin** [confirmedcode/Lockdown-Mac#15]
There exists an edge case where the Secure Tunnel or Firewall will be stuck on "Deactivating" for some time before it actually deactivates. We should force the deactivation.

**Comment by hijohnnylin** [comment]
Implemented in 6446ca29319c171524b0ee455453c6a3c79e9a4f. Currently verifying.

**Comment by CruiseMan** [comment]
> Implemented in [6446ca2](https://github.com/confirmedcode/Lockdown-Mac/commit/6446ca29319c171524b0ee455453c6a3c79e9a4f). Currently verifying.

Is this still under verification ?

**Comment by hijohnnylin** [comment]
Still intermittently seeing this behavior, but this is old enough to close.
