### ISSUE TITLE
Not able to see domaine due to logn subdomaine

### ISSUE THREAD

**Issue by CruiseMan** [confirmedcode/Lockdown-Mac#22]
<img width="381" alt="Screen Shot 2021-09-30 at 11 18 43 AM" src="https://user-images.githubusercontent.com/15807643/135509614-db85bd26-dbf8-4baf-964b-0559bfb4410f.png">

**Comment by hijohnnylin** [comment]
Fixed in bf76106343db18aae4b11dcfb6e9bff78cfc6ed3, closing.
