### ISSUE TITLE
Uninstalling the app breaks website.

### ISSUE THREAD

**Issue by applLvr777** [confirmedcode/Lockdown-Mac#28]
If I uninstall the app following the instrcutions displayed on their website, some sites will stop working.
For example, I cannot even connect to the Youtube server anymore. I cannot load Twitter feeds either. Re-installing the app fixes the problem. So long story short, the app has to be running in order for the network to work properly, and that's clearly an issue for users trying to uninstall the app.

**Comment by hijohnnylin** [comment]
Sorry about that. I'm no longer the main maintainer of this repository, so you should reach out to team@lockdownprivacy.com for support.

However, it sounds like either "Lockdown Configuration" and/or "Lockdown VPN" was not uninstalled. Did you follow step 6 and 7? They're separate and both must be removed.

"6) On the left, select "Lockdown Configuration", then click the "-" minus icon (on the bottom left of this dialog box)
7) On the left again, select "Lockdown VPN", then click the "-" minus icon again"

**Comment by applLvr777** [comment]
Yes I did.

**Comment by shalloran** [comment]
Resolved this issue with @sshibashi777
