### ISSUE TITLE
Add trackers to the provided lists?

### ISSUE THREAD

**Issue by mthld** [confirmedcode/Lockdown-Mac#4]
Hi,

There is a lot of trackers who aren't currently blocked (that are by uBlock Origin), is it possible to add them to the official lists? How can we improve that? Is there a particular workflow (like submitting a type of PR) we can follow?

Thanks in advance,

**Comment by hijohnnylin** [comment]
You can just create an issue with the trackers you'd like to add.

I'l add to the README about how to contribute adding trackers.

FWIW, we are pretty strict with what gets added - tons of lists online have thousands of domains/hosts, most of them outdated, some of them formatted incorrectly, and almost always just copy-pasted/franken-merged from various random lists online. When some website/app breaks as a result of adding 10,000 domains, it ends up with a lot of unhappy users. We try to avoid adding whatever lists we find online for this reason.

**Comment by mthld** [comment]
Thanks for answering, however I don't use Lockdown anymore but switched to Wipr.

**Comment by hijohnnylin** [comment]
Hi @mthld, thanks for following up!

As a final FYI, Wipr does not block ads+trackers in actual iOS apps, only in Safari and when apps use Safari to display content. So you are still being tracked by Facebook, analytics, marketing, data-selling firms etc when you use Wipr. It is also closed source, so you don't know what the app is doing with your data.

Lockdown blocks ads and trackers in *all* apps, regardless of whether or not they're using Safari, so it does block Facebook/other data trackers. And it's open source. Not to mention it's free, vs Wipr which is paid.

Hope this is a helpful clarification!
