### ISSUE TITLE
Firewall not loading 

### ISSUE THREAD

**Issue by sahilc0** [confirmedcode/Lockdown-Mac#5]
MacOS Catalina, latest Lockdown.
Clicking the on button to turn on firewall, glitches and turns on and off, doesn't work. If not disabled quickly, it blocks internet access. So have to quit the app.

Video is in zip file

[Screen Recording 2020-02-21 at 11.29.23 PM.mov.zip](https://github.com/confirmedcode/Lockdown-Mac/files/4238949/Screen.Recording.2020-02-21.at.11.29.23.PM.mov.zip)

**Comment by sahilc0** [comment]
Update: I found that if I turn off my VPN (Mullvad), Lockdown works fine.

So there's some clashing with Mullvad going on here. Any ideas?

**Comment by workingDog** [comment]
Hi @sahilc0 ,

are you using Lockdown from the Apple store or did you compile the github code? 
I'm asking because I cannot make the github code work.

**Comment by sahilc0** [comment]
Hey it's from the app store!

**Comment by bong0** [comment]
> Update: I found that if I turn off my VPN (Mullvad), Lockdown works fine.
> 
> So there's some clashing with Mullvad going on here. Any ideas?
I confirm this happens as well with Tunnelblick (openvpn). Turning off openvpn, Lockdown on, then openvpn on works though. So the order is important (but not controllable when both VPNs are in autostart)

**Comment by sahilc0** [comment]
This ticket was closed, after I got an email from a (I think) developer that there isn't time to test compatibility with other VPNs. https://github.com/confirmedcode/Lockdown-Mac/issues/11

Seems strange to me considering Adguard works, and other VPNs are not working either. It is true that they are selling a VPN as well, but probably not worth my time to get conspiratorial here.

**Comment by bong0** [comment]
@sahilc0 thanks for pointing me at this. I don't get why they don't allow other VPNs to work in parallel (like to actually access private networks, not for hiding the public IP) 🤔

**Comment by hijohnnylin** [comment]
hey folks, just got these notifications. thanks for your interest! 😀
if you have specific compatibility issues with other apps, the quickest way to reach us is at: team@lockdownhq.com

**Comment by sahilc0** [comment]
Hold on @hijohnnylin - that’s exactly what I did and you told me you wouldn’t work with specific compatibility issues.
