### ISSUE TITLE
High energy usage

### ISSUE THREAD

**Issue by orthodoX** [confirmedcode/Lockdown-Mac#9]
I'm monitoring the energy impact of my apps in the past few days, and I'm noticing that Lockdown is in my top 3.

<img width="838" alt="Screenshot 2020-03-10 at 09 13 24" src="https://user-images.githubusercontent.com/370935/76299563-99fb2180-62bb-11ea-8bad-fe72d65c4726.png">

**Comment by hijohnnylin** [comment]
Looking into this now - initial hunch is that it might be a SwiftUI bug/issue, but will investigate.

**Comment by hijohnnylin** [comment]
Should be fixed in new update, rolling out now.
